#!/usr/bin/env ansible-playbook
- hosts: localhost
  connection: local

  vars:
    packages:
    - nginx
    - ntp

    services:
    - nginx
    - ntp

    firewall_inbound_ports:
    - 80
    - 22

  tasks:
  - name: Enable Ubuntu Firewall (ufw) and deny everything.
    ufw:
      state=enabled
      policy=deny

  - name: Turn off the logging
    ufw: logging=off

  - name: Allow Inbound Traffic
    ufw: rule=allow port={{ item }} proto=tcp
    with_items:
        - "{{ firewall_inbound_ports }}"

  - name: Update apt cache if needed.
    apt: update_cache=yes cache_valid_time=3600

  - name: "Install Base Packages"
    apt: name={{ item }} state=latest
    with_items:
      - "{{ packages }}"

  - name: Start services.
    service: >
      name={{ item }}
      state=started
      enabled=yes
    with_items:
      - "{{ services }}"
